services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: uniasselvi
      POSTGRES_PASSWORD: uniasselvi
      POSTGRES_DB: uniasselvi_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U uniasselvi"]
      interval: 5s
      start_period: 5s

volumes:
  postgres_data:
